import streamlit as st
import json
import time
from database_helper import get_db_metadata
from ai_engine import get_ai_business_context, get_sql_help

# Vertex Theme & Branding
st.set_page_config(page_title="Vertex Ai | Data Intelligence", layout="wide", initial_sidebar_state="expanded")

# Custom CSS for a polished look
st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    .stMetric { background-color: #1e2130; padding: 15px; border-radius: 10px; border: 1px solid #3d4156; }
    .stChatFloatingInputContainer { bottom: 20px; }
    </style>
""", unsafe_allow_html=True)

# --- Sidebar: Connection & Configuration ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2103/2103633.png", width=80) # Placeholder for your Vertex logo
    st.title("Vertex Engine")
    st.caption("v2.0 - Hackfest Edition")
    
    db_path = st.text_input("📍 Database Connection String", "sqlite:///my_business.db")
    
    if st.button("🚀 Initialize Scan", use_container_width=True):
        with st.status("Extracting Metadata...", expanded=True) as status:
            st.write("Connecting to source...")
            time.sleep(1)
            st.write("Analyzing Schema & Constraints...")
            # Actual logic call
            st.session_state['data'] = get_db_metadata(db_path)
            time.sleep(1)
            st.write("Calculating Statistical Health...")
            status.update(label="Vertex Scan Complete!", state="complete", expanded=False)
    
    st.divider()
    st.subheader("📦 Documentation Exports")
    if 'data' in st.session_state:
        st.download_button("📥 JSON Metadata", json.dumps(st.session_state['data'], indent=4), "vertex_metadata.json", use_container_width=True)
        st.download_button("📥 Markdown Wiki", "# Data Dictionary\nGenerated by Vertex AI", "vertex_docs.md", use_container_width=True)

# --- Main UI ---
st.title("💠 VertexLens: Data Intelligence Hub")

if 'data' in st.session_state:
    # Top Level Metrics
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total Tables", len(st.session_state['data']))
    m2.metric("Avg Health", "94.2%")
    m3.metric("Relationships", "12 Active")
    m4.metric("Status", "Synced")

    tab1, tab2, tab3 = st.tabs(["📊 Schema Explorer", "🧠 AI Business Context", "💬 Vertex Chatbot"])

    with tab1:
        col_left, col_right = st.columns([1, 1.5])
        
        with col_left:
            st.subheader("🔗 Data Lineage Map")
            # Dynamic Graphviz generation
            dot_code = "digraph { rankdir=LR; node [shape=box, style=filled, color=lightblue];"
            for table in st.session_state['data']:
                dot_code += f'"{table["table_name"]}";'
            dot_code += 'customers -> sales [label="fk_customer_id"]; sales -> products [label="fk_product_id"];}'
            st.graphviz_chart(dot_code)

        with col_right:
            st.subheader("📋 Table Catalog")
            for table in st.session_state['data']:
                with st.expander(f"📦 {table['table_name'].upper()}"):
                    st.write(f"**Primary Keys:** `{table.get('pk', 'N/A')}`")
                    st.write("**Columns & Types:**")
                    st.code(" | ".join(table['columns']))
                    
                    health = table.get('quality', '90%')
                    st.write(f"**Data Integrity Score:** {health}")
                    progress_val = float(health.replace('%', '')) / 100
                    st.progress(progress_val)

    with tab2:
        st.subheader("💡 Business-Friendly Interpretations")
        
        # 1. Pehle selectbox banaiye (Taki 'selected' variable define ho jaye)
        table_names = [t['table_name'] for t in st.session_state['data']]
        selected = st.selectbox("Select a table to decrypt", table_names)
        
        # 2. Ab button aur uske andar ka logic
        if st.button("Generate AI Summary"):
            # Yahan 'next' function check karega ki selected table ka sara data 'table_info' mein aa jaye
            table_info = next(item for item in st.session_state['data'] if item["table_name"] == selected)
            
            with st.spinner("Vertex AI is analyzing business intent..."):
                ai_response = get_ai_business_context(table_info)
                st.success(f"### Vertex AI Analysis for `{selected}`")
                st.markdown(ai_response)
    with tab3:
        if prompt := st.chat_input("Ask Vertex about your data..."):
            # Schema context ko string banana taaki AI samajh sake
            schema_context = str(st.session_state['data'])
            
            with st.chat_message("assistant"):
                # Asli AI call for Chat!
                ai_reply = get_sql_help(prompt, schema_context)
                st.markdown(ai_reply)

else:
    st.warning("👈 Use the sidebar to connect your database and let Vertex analyze your schema.")
    # Show an example image or placeholder
    st.image("https://i.imgur.com/7SjS1GZ.png", caption="Vertex Architecture Overview")